server:
  port: 9010

spring:
  application:
    name: emart-api-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: 
          true
      ribbon: 
        enabled:
          true

zuul:
  routes:
    emart-user-service:
      path: /user/**
      sensitiveHeaders: Cookie,Set-Cookie
      service-id: emart-user-service
    emart-order-service:
      path: /order/**
      sensitiveHeaders: Cookie,Set-Cookie
      service-id: emart-order-service
    emart-item-service:
      path: /item/**
      sensitiveHeaders: Cookie,Set-Cookie
      service-id: emart-item-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 50000
